# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-19 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas', '0003_kelas_mapel_pengajar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kelas',
            name='kelas',
        ),
        migrations.AlterField(
            model_name='kelas',
            name='nama_kelas',
            field=models.CharField(max_length=10),
        ),
    ]
