# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-26 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0002_siswa_kelas_sekarang'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='foto',
            field=models.ImageField(blank=True, upload_to='/home/aris/PycharmProjects/akademik/assets/upload'),
        ),
    ]
