# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-18 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('nip', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('alamat', models.TextField(blank=True)),
                ('tgl_lahir', models.DateField()),
                ('telepon', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
