# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-31 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0002_guru_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='foto',
            field=models.ImageField(blank=True, upload_to='/home/aris/PycharmProjects/akademik/assets/upload/guru'),
        ),
    ]
