# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-18 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kelas', '0001_initial'),
        ('siswa', '0001_initial'),
        ('guru', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raport',
            fields=[
                ('id_raport', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
                ('harian', models.FloatField(null=True)),
                ('uts', models.FloatField(null=True)),
                ('uas', models.FloatField(null=True)),
                ('id_guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guru.Guru')),
                ('id_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kelas.Kelas')),
                ('id_mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kelas.Mapel')),
                ('id_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.Siswa')),
            ],
        ),
    ]
