# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-19 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kelas', '0003_kelas_mapel_pengajar'),
        ('raport', '0004_auto_20160719_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='raport',
            name='id_kelas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kelas.Kelas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raport',
            name='id_mapel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kelas.Mapel'),
            preserve_default=False,
        ),
    ]
