# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-30 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raport', '0009_auto_20160726_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raport',
            name='harian',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='raport',
            name='uas',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='raport',
            name='uts',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
