# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raport', '0011_auto_20160731_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='raport',
            name='tahun_ajaran',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
